const toggle=document.querySelector('.menu-toggle');
const nav=document.querySelector('.nav-links');
toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',open);document.body.classList.toggle('menu-open',open)});
document.querySelectorAll('.nav-links a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');toggle.setAttribute('aria-expanded','false');document.body.classList.remove('menu-open')}));
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});
document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
document.getElementById('year').textContent=new Date().getFullYear();
const lightbox=document.querySelector('.lightbox');
const lightboxImg=lightbox.querySelector('img');
document.querySelectorAll('.gallery-item').forEach(button=>button.addEventListener('click',()=>{lightboxImg.src=button.dataset.src;lightbox.hidden=false;document.body.style.overflow='hidden'}));
function closeLightbox(){lightbox.hidden=true;lightboxImg.src='';document.body.style.overflow=''}
lightbox.querySelector('.lightbox-close').addEventListener('click',closeLightbox);
lightbox.addEventListener('click',e=>{if(e.target===lightbox)closeLightbox()});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!lightbox.hidden)closeLightbox()});
  const data=new FormData(e.currentTarget);
  const subject=encodeURIComponent(`Reservation inquiry - ${data.get('booking')}`);
  const body=encodeURIComponent(`Hello Inocencia Private Resort,\n\nI would like to inquire about a reservation.\n\nName: ${data.get('name')}\nPhone: ${data.get('phone')}\nEmail: ${data.get('email')}\nPreferred date: ${data.get('date')}\nNumber of guests: ${data.get('guests')}\nBooking type: ${data.get('booking')}\n\nMessage:\n${data.get('message')||'No additional message'}\n\nThank you.`);
  document.getElementById('formNote').textContent='Opening your email app…';
  window.location.href=`mailto:inocenciaprivateresort@gmail.com?subject=${subject}&body=${body}`;
});
